# Generated by Django 5.1.2 on 2024-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echo',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
